### ISSUE TITLE
npm start copies url to my clipboard

### ISSUE THREAD

**Issue by allieoop** [living-room/lovelace#41]
Every time you run `npm start` the contents on your clipboard are automatically replaced with `http://localhost:5000`.

**Comment by jedahan** [comment]
Is it cool that we keep the 'open localhost:5000' without copying to clipboard?

**Comment by jedahan** [comment]
These issues have been making things a lot nicer, thanks for reporting!

<img width="324" alt="screen shot 2018-05-31 at 2 39 10 pm" src="https://user-images.githubusercontent.com/32407/40801242-726d735a-64e0-11e8-991e-8b88bb79f271.png">

For context, I was using zeit/serve@6, and it automatically did stuff like this. I changed service-js to use zeit/serve@7 which is way less opinionated, and manually open http://localhost:5000 now.
